name: zidney
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futur.ttf
        - asset: assets/fonts/Futura Bold font.ttf
          weight: 700
        - asset: assets/fonts/Futura Bold Italic font.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Futura Book font.ttf
        - asset: assets/fonts/Futura Book Italic font.ttf
          style: italic
        - asset: assets/fonts/Futura Extra Black font.ttf
        - asset: assets/fonts/Futura Heavy font.ttf
          weight: 800
        - asset: assets/fonts/Futura Heavy Italic font.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/futura light bt.ttf
          weight: 300
        - asset: assets/fonts/Futura Light font.ttf
          weight: 300
        - asset: assets/fonts/Futura Light Italic font.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/futura medium bt.ttf
          weight: 500
        - asset: assets/fonts/futura medium condensed bt.ttf
          weight: 500
        - asset: assets/fonts/Futura Medium Italic font.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Futura XBlk BT.ttf
          weight: 900
        - asset: assets/fonts/tt0205m_.ttf
        - asset: assets/fonts/unicode.futurab.ttf
        - asset: assets/fonts/unicode.futurabb.ttf
